#!/bin/bash
while true
do
clear

dropb () {
port_dropbear=`ps aux | grep dropbear | awk NR==1 | awk '{print $17;}'`
log=/var/log/auth.log
loginsukses='Password auth succeeded'
clear
pids=`ps ax |grep dropbear |grep  " $port_dropbear" |awk -F" " '{print $1}'`
for pid in $pids
do
pidlogs=`grep $pid $log |grep "$loginsukses" |awk -F" " '{print $3}'`
i=0
for pidend in $pidlogs
do
let i=i+1
done
if [ $pidend ];then
login=`grep $pid $log |grep "$pidend" |grep "$loginsukses"`
PID=$pid
user=`echo $login |awk -F" " '{print $10}' | sed -r "s/'/ /g"`
waktu=`echo $login |awk -F" " '{print $2"-"$1,$3}'`
while [ ${#waktu} -lt 13 ]; do
waktu=$waktu" "
done
while [ ${#user} -lt 16 ]; do
user=$user" "
done
while [ ${#PID} -lt 8 ]; do
PID=$PID" "
done
echo "$user $PID $waktu"
fi
done
}


killing () {
	kill $1
}
for user in $(cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog' | awk -F: '{print $1}'); do
num=$(dropb | grep "$user" | wc -l)
limit=$(cat /etc/ADMcgh/userDIR/$user | grep "limite" | awk '{print $2}')
[[ $limit = "HWID" ]] && limit=1
if [ "$num" -gt "$limit" ]; then
pidKILL=$(dropb | grep "$user" | awk '{print $2}')
killing $pidKILL
echo " $user DROPBEAR LIMITADO EN SU ${s1ssh} CONEXION!" >> $HOME/limiter.log
fi
sleep 2s
done
